# Generated by Django 5.2.5 on 2026-04-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_imagen_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaFotos',
            fields=[
                ('idgaleria', models.AutoField(db_column='idgaleria', primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Galeria_fotos',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
